### ISSUE TITLE
How to get PTT

### ISSUE THREAD

**Issue by sentausa** [KBoehme/TnSeq-Pipeline#1]
Hi, I'd like to use this pipeline, but I don't know what is a Genbank PTT file. And how can we get it? Thank you.

**Comment by KBoehme** [comment]
You can see here about what .ptt files are: https://www.biostars.org/p/16405/

It seems they are a bit of a legacy format and so you might have to find a newer format and a corresponding tool to convert it into .ptt files.

**Comment by sentausa** [comment]
Thanks. I should have Googled it first.
