### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by petemeng** [KBoehme/TnSeq-Pipeline#3]
> python TnSeq-Pipeline.py example_data/example2.config 
  File "TnSeq-Pipeline.py", line 117
    print "Transposon parameter was empty. This means no check will be made for a transposon sequence and all reads will move to the mapping stage."
                                                                                                                                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Transposon parameter was empty. This means no check will be made for a transposon sequence and all reads will move to the mapping stage.")?

**Comment by KBoehme** [comment]
Seems its a python2 vs python3 thing. The script is meant to be run with python2, however, I created a branch called `py3` that should work with python3. I haven't tested it but if you run into any more issues with this new branch let me know.

The branch can be found here: https://github.com/KBoehme/TnSeq-Pipeline/tree/py3

**Comment by petemeng** [comment]
ok. Thank you very much



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 11, 2022 00:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [KBoehme/TnSeq-Pipeline] SyntaxError: Missing parentheses in call to 'print'. (Issue #3)




 
Seems its a python2 vs python3 thing. I created a branch called py3 that should work with python3. I haven't tested it but if you run into any more issues with this new branch let me know.
